### ISSUE TITLE
Add these two asynchronous functions and then bring them all into line

### ISSUE THREAD

**Issue by jecs-imperial** [djalbat/Necessary#1]
function forEach(callback, done, context) {
      function next() {
        callback(next, done, context);
      }
  
      next();
    }
  
    function sequence(callbacks, done, context) {
      let index = 0;
  
      function next() {
        const callback = callbacks[index++];
  
        if (callback === undefined) {
          done();
        } else {
          callback(next, done, context);
        }
      }
  
      next();
    };

Note that the callback signatures differ from the existing functions. Here, callbacks are given both the `next()` and `done()` methods.

**Comment by djalbat** [comment]
Done.
